import json

files = [
    "/workspace/README.md",
    "/workspace/design-md/airbnb/DESIGN.md",
    "/workspace/design-md/airbnb/README.md",
    "/workspace/design-md/airtable/DESIGN.md",
    "/workspace/design-md/airtable/README.md",
    "/workspace/design-md/apple/DESIGN.md",
    "/workspace/design-md/apple/README.md",
    "/workspace/design-md/bmw/DESIGN.md",
    "/workspace/design-md/bmw/README.md",
    "/workspace/design-md/cal/DESIGN.md",
    "/workspace/design-md/cal/README.md",
    "/workspace/design-md/claude/DESIGN.md",
    "/workspace/design-md/claude/README.md",
    "/workspace/design-md/clay/DESIGN.md",
    "/workspace/design-md/clay/README.md",
    "/workspace/design-md/clickhouse/DESIGN.md",
    "/workspace/design-md/clickhouse/README.md",
    "/workspace/design-md/cohere/DESIGN.md",
    "/workspace/design-md/cohere/README.md",
    "/workspace/design-md/coinbase/DESIGN.md",
    "/workspace/design-md/coinbase/README.md",
    "/workspace/design-md/composio/DESIGN.md",
    "/workspace/design-md/composio/README.md",
    "/workspace/design-md/cursor/DESIGN.md",
    "/workspace/design-md/cursor/README.md",
    "/workspace/design-md/elevenlabs/DESIGN.md",
    "/workspace/design-md/elevenlabs/README.md",
    "/workspace/design-md/expo/DESIGN.md",
    "/workspace/design-md/expo/README.md",
    "/workspace/design-md/ferrari/DESIGN.md",
    "/workspace/design-md/ferrari/README.md",
    "/workspace/design-md/figma/DESIGN.md",
    "/workspace/design-md/figma/README.md",
    "/workspace/design-md/framer/DESIGN.md",
    "/workspace/design-md/framer/README.md",
    "/workspace/design-md/hashicorp/DESIGN.md",
    "/workspace/design-md/hashicorp/README.md",
    "/workspace/design-md/ibm/DESIGN.md",
    "/workspace/design-md/ibm/README.md",
    "/workspace/design-md/intercom/DESIGN.md",
    "/workspace/design-md/intercom/README.md",
    "/workspace/design-md/kraken/DESIGN.md",
    "/workspace/design-md/kraken/README.md",
    "/workspace/design-md/lamborghini/DESIGN.md",
    "/workspace/design-md/lamborghini/README.md",
    "/workspace/design-md/linear.app/DESIGN.md",
    "/workspace/design-md/linear.app/README.md",
    "/workspace/design-md/lovable/DESIGN.md",
    "/workspace/design-md/lovable/README.md",
    "/workspace/design-md/minimax/DESIGN.md",
    "/workspace/design-md/minimax/README.md",
    "/workspace/design-md/mintlify/DESIGN.md",
    "/workspace/design-md/mintlify/README.md",
    "/workspace/design-md/miro/DESIGN.md",
    "/workspace/design-md/miro/README.md",
    "/workspace/design-md/mistral.ai/DESIGN.md",
    "/workspace/design-md/mistral.ai/README.md",
    "/workspace/design-md/mongodb/DESIGN.md",
    "/workspace/design-md/mongodb/README.md",
    "/workspace/design-md/notion/DESIGN.md",
    "/workspace/design-md/notion/README.md",
    "/workspace/design-md/nvidia/DESIGN.md",
    "/workspace/design-md/nvidia/README.md",
    "/workspace/design-md/ollama/DESIGN.md",
    "/workspace/design-md/ollama/README.md",
    "/workspace/design-md/opencode.ai/DESIGN.md",
    "/workspace/design-md/opencode.ai/README.md",
    "/workspace/design-md/pinterest/DESIGN.md",
    "/workspace/design-md/pinterest/README.md",
    "/workspace/design-md/posthog/DESIGN.md",
    "/workspace/design-md/posthog/README.md",
    "/workspace/design-md/raycast/DESIGN.md",
    "/workspace/design-md/raycast/README.md",
    "/workspace/design-md/renault/DESIGN.md",
    "/workspace/design-md/renault/README.md",
    "/workspace/design-md/replicate/DESIGN.md",
    "/workspace/design-md/replicate/README.md",
    "/workspace/design-md/resend/DESIGN.md",
    "/workspace/design-md/resend/README.md",
    "/workspace/design-md/revolut/DESIGN.md",
    "/workspace/design-md/revolut/README.md",
    "/workspace/design-md/runwayml/DESIGN.md",
    "/workspace/design-md/runwayml/README.md",
    "/workspace/design-md/sanity/DESIGN.md",
    "/workspace/design-md/sanity/README.md",
    "/workspace/design-md/sentry/DESIGN.md",
    "/workspace/design-md/sentry/README.md",
    "/workspace/design-md/spacex/DESIGN.md",
    "/workspace/design-md/spacex/README.md",
    "/workspace/design-md/spotify/DESIGN.md",
    "/workspace/design-md/spotify/README.md",
    "/workspace/design-md/stripe/DESIGN.md",
    "/workspace/design-md/stripe/README.md",
    "/workspace/design-md/supabase/DESIGN.md",
    "/workspace/design-md/supabase/README.md",
    "/workspace/design-md/superhuman/DESIGN.md",
    "/workspace/design-md/superhuman/README.md",
    "/workspace/design-md/tesla/DESIGN.md",
    "/workspace/design-md/tesla/README.md",
    "/workspace/design-md/together.ai/DESIGN.md",
    "/workspace/design-md/together.ai/README.md",
    "/workspace/design-md/uber/DESIGN.md",
    "/workspace/design-md/uber/README.md",
    "/workspace/design-md/vercel/DESIGN.md",
    "/workspace/design-md/vercel/README.md",
    "/workspace/design-md/voltagent/DESIGN.md",
    "/workspace/design-md/voltagent/README.md",
    "/workspace/design-md/warp/DESIGN.md",
    "/workspace/design-md/warp/README.md",
    "/workspace/design-md/webflow/DESIGN.md",
    "/workspace/design-md/webflow/README.md",
    "/workspace/design-md/wise/DESIGN.md",
    "/workspace/design-md/wise/README.md",
    "/workspace/design-md/x.ai/DESIGN.md",
    "/workspace/design-md/x.ai/README.md",
    "/workspace/design-md/zapier/DESIGN.md",
    "/workspace/design-md/zapier/README.md",
    "/workspace/test_fail.py",
    "/workspace/test_full.py",
    "/workspace/test_marker_trans.py",
    "/workspace/test_markers.py",
    "/workspace/test_markers2.py",
    "/workspace/test_markers3.py",
    "/workspace/test_out.md",
    "/workspace/test_parse.py",
    "/workspace/test_trans.py",
    "/workspace/test_trans2.py",
    "/workspace/test_trans3.py",
    "/workspace/test_trans4.py",
    "/workspace/test_trans5.py",
    "/workspace/test_trans_block.py",
    "/workspace/test_trans_block2.py",
    "/workspace/test_ws.py",
    "/workspace/translate_all.py"
]

print("此次合并的主要目的是将项目中的英文文档（包括根目录 README.md 和所有组件的 DESIGN.md、README.md）批量翻译为中文。同时，引入了自动解析和翻译 Markdown 文件的 Python 脚本及其相关测试文件，以支持整个翻译流程的自动化与验证。")
print("| 文件 | 变更 |")
print("|------|---------|")
for file in files:
    rel_path = file.replace("/workspace/", "")
    if file.endswith(".md") and not file.startswith("/workspace/test_out.md"):
        print(f"| {rel_path} | - 将文件内容从英文翻译为中文 |")
    elif file == "/workspace/test_out.md":
        print(f"| {rel_path} | - 新增用于验证翻译输出结果的 Markdown 测试文件 |")
    elif file.startswith("/workspace/test_"):
        print(f"| {rel_path} | - 新增测试脚本以验证 Markdown 解析和翻译功能 |")
    elif file == "/workspace/translate_all.py":
        print(f"| {rel_path} | - 新增核心脚本，使用 deep_translator 实现 Markdown 文件的自动化解析与中文翻译 |")

